### ISSUE TITLE
Provide an example of using custom error messages with complex object

### ISSUE THREAD

**Issue by b-ponomarenko** [philipnilsson/bueno#2]
Hi! Our team has been thinking about using this library for validation, but I'm not sure how to create custom error messages for complex schemas. I found an example [here](https://github.com/philipnilsson/bueno/blob/master/src/docs/customizing-errors.md), but there is no example of using custom error messages for each validation. Let me show an example:
```js
const schema = object({
  firstName: string(not(length(0))),
  secondName: string(not(length(0))),
  age: number(atLeast(18)),
  email: string(email)
})
```

How to create custom error message for each field and for each validation in this case?

**Comment by philipnilsson** [comment]
Hey @b-ponomarenko,

Sorry for the late response (vacation :). Happy to hear you've been evaluating Bueno for your team! If you're still considering it I'll try to help you with what you need. If you decided on something else it'd still be great if I could use this to improve the documentation, so would be happy to get your feedback on improving it after resolving this issue.

If you could give me an example of the error message you're looking for for a specific input that would be the great (and whether you'd like to support multiple locales or not).

Based on what you've explained I'm going to guess the approach you need is to simply call `setMessage` on the individual validator as follows.

```typescript
const schema = object({
  firstName: setMessage(string(not(length(0))), 'No empty first names please!'),
  secondName: string(not(length(0))),
  age: setMessage(number(atLeast(18)), 'No minors allowed :('),
  email: string(email)
})
```

Let me know if that helped.

Philip

**Comment by b-ponomarenko** [comment]
Thank you for answer and great example. Yes, that is what I’m talking about. In case when I want to create different error messages for different validates I have to wrap every validator in `setMessage`? Could you tell me it is possible to pass second parameter to `setMessage` as a function and have access to form payload in order to create dynamic error messages, like
```js
setMessage(validator, (values) => `${values.email} is incorrect`
```

**Comment by philipnilsson** [comment]
>  I have to wrap every validator in setMessage?

I don't understand what else you'd expect? `setMessage` returns a new schema, so you can do

```ts
const phoneNumber = 
  setMessage(number, 'A valid phone number')
```

and then use it as 

```ts
const contact = object({ 
  homeNumber: phoneNumber, 
  businessNumber: phoneNumber
})
```

>  and have access to form payload in order to create dynamic error messages

There is a general purpose combinator for "self-reference" in bueno, i.e. creating combinators that are based on the value they're trying to validate, called `self`

```ts
 const selfValidator = self<{ email : string }>(my => object({
    email: setMessage(email, `${my.email} is not a valid email`)
 }))
```

a test would look like this

```ts
it('reports the email address dynamically in errors', () => {
  expect(parse({ email: 'foo@bar' }, selfValidator, enUS).errorsByKey).toEqual({
    email: 'Foo@bar is not a valid email',
  })
})
```
